csc440::nuf::ViewMessageActivity
final int csc440.nuf.ViewMessageActivity.REQ_CODE_PLAYER
ScrollItemManager csc440.nuf.ViewMessageActivity.items
Bundle csc440.nuf.ViewMessageActivity.state
ActionBar csc440.nuf.ViewMessageActivity._actionBar
boolean csc440.nuf.ViewMessageActivity.playPressed
int csc440.nuf.ViewMessageActivity.startTime
boolean csc440.nuf.ViewMessageActivity.autoPlay
AlertDialog csc440.nuf.ViewMessageActivity.alertAutoPlay
void csc440.nuf.ViewMessageActivity.onCreate(Bundle savedInstanceState)
References csc440.nuf.ViewMessageActivity.onClick, csc440.nuf.ViewMessageActivity.playMessage, csc440.nuf.ActionBar.setTitle, csc440.nuf.ActionBar.setHomeListener, csc440.nuf.ScrollItemManager.addItem, csc440.nuf.ScrollItemManager.setTitle, csc440.nuf.ScrollItemManager.setIcon, csc440.nuf.ScrollItemManager.setListener, csc440.nuf.ScrollItemManager.addToLinear, csc440.nuf.ScrollItemManager.addLine.
void csc440.nuf.ViewMessageActivity.playMessage(boolean playPressed)
Referenced by csc440.nuf.ViewMessageActivity.onCreate, csc440.nuf.ViewMessageActivity.onResume, csc440.nuf.ViewMessageActivity.onClick.
void csc440.nuf.ViewMessageActivity.onClick(View v)
References csc440.nuf.ViewMessageActivity.playMessage.
Referenced by csc440.nuf.ViewMessageActivity.onCreate.
void csc440.nuf.ViewMessageActivity.onResume()
References csc440.nuf.ViewMessageActivity.playMessage.
void csc440.nuf.ViewMessageActivity.onActivityResult(int requestCode, int resultCode, Intent data)