csc440::nuf::server::SMILMessage
String csc440.nuf.server.SMILMessage.sender
String csc440.nuf.server.SMILMessage.recipient
String csc440.nuf.server.SMILMessage.senderEmail
String csc440.nuf.server.SMILMessage.recipientEmail
File csc440.nuf.server.SMILMessage.SMILFile
Long csc440.nuf.server.SMILMessage.id
csc440.nuf.server.SMILMessage.SMILMessage(File file, String sender, String recipient, String senderEmail, String recipientEmail)
References csc440.nuf.server.SMILMessage.setSender, csc440.nuf.server.SMILMessage.setRecipient.
String csc440.nuf.server.SMILMessage.getSenderEmail()
void csc440.nuf.server.SMILMessage.setSenderEmail(String senderEmail)
Referenced by csc440.nuf.server.DataStore.update, csc440.nuf.server.SMILEngineService.updateSMILMessage.
String csc440.nuf.server.SMILMessage.getRecipientEmail()
void csc440.nuf.server.SMILMessage.setRecipientEmail(String recipientEmail)
File csc440.nuf.server.SMILMessage.getSMILFile()
void csc440.nuf.server.SMILMessage.setSMILFile(File sMILFile)
Long csc440.nuf.server.SMILMessage.getId()
Referenced by csc440.nuf.server.SMILEngineService.updateSMILMessage, csc440.nuf.server.SMILEngineService.deleteSMILMessage.
void csc440.nuf.server.SMILMessage.setId(Long id)
Referenced by csc440.nuf.server.DataStore.update.
String csc440.nuf.server.SMILMessage.getSender()
void csc440.nuf.server.SMILMessage.setSender(String sender)
Referenced by csc440.nuf.server.SMILMessage.SMILMessage.
String csc440.nuf.server.SMILMessage.getRecipient()
void csc440.nuf.server.SMILMessage.setRecipient(String recipient)
Referenced by csc440.nuf.server.SMILMessage.SMILMessage.