csc440::nuf::Util
final String csc440.nuf.Util.TAG
Tag for logging.
final String csc440.nuf.Util.SHARED_PREFS
Key for shared preferences.
final Map<Context, String> csc440.nuf.Util.URL_MAP
Cache containing the base URL for a given context.
final String csc440.nuf.Util.ACCOUNT_NAME
Key for account name in shared preferences.
Referenced by csc440.nuf.DeviceRegistrar.registerOrUnregister.
final String csc440.nuf.Util.AUTH_COOKIE
Key for auth cookie name in shared preferences.
Referenced by csc440.nuf.Util.getRequestFactory, csc440.nuf.DeviceRegistrar.registerOrUnregister.
final String csc440.nuf.Util.CONNECTION_STATUS
Key for connection status in shared preferences.
Referenced by csc440.nuf.SMILActivity.onResume.
final String csc440.nuf.Util.CONNECTED
Value for CONNECTION_STATUS key.
final String csc440.nuf.Util.CONNECTING
Value for CONNECTION_STATUS key.
final String csc440.nuf.Util.DISCONNECTED
Value for CONNECTION_STATUS key.
Referenced by csc440.nuf.SMILActivity.onResume.
final String csc440.nuf.Util.DEVICE_REGISTRATION_ID
Key for device registration id in shared preferences.
Referenced by csc440.nuf.AccountsActivity.onCreate, csc440.nuf.C2DMReceiver.onUnregistered, csc440.nuf.DeviceRegistrar.registerOrUnregister.
final String csc440.nuf.Util.RF_METHOD
Referenced by csc440.nuf.Util.getRequestFactory.
final String csc440.nuf.Util.UPDATE_UI_INTENT
An intent name for receiving registration/unregistration status.
Referenced by csc440.nuf.C2DMReceiver.onError, csc440.nuf.DeviceRegistrar.registerOrUnregister, csc440.nuf.SMILActivity.onCreate.
static void csc440.nuf.Util.generateNotification(Context context, String message)
Display a notification containing the given string.
References csc440.nuf.Util.getSharedPreferences.
Referenced by csc440.nuf.MessageDisplay.displayMessage.
static String csc440.nuf.Util.getBaseUrl(Context context)
Returns the (debug or production) URL associated with the registration service.
References csc440.nuf.Setup.PROD_URL.
Referenced by csc440.nuf.Util.getRequestFactory, csc440.nuf.Util.isDebug.
static <TextendsRequestFactory> T csc440.nuf.Util.getRequestFactory(Context context, Class< T > factoryClass)
Creates and returns an initialized RequestFactory of the given type.
References csc440.nuf.Util.getSharedPreferences, csc440.nuf.Util.AUTH_COOKIE, csc440.nuf.Util.getBaseUrl, csc440.nuf.Util.RF_METHOD.
Referenced by csc440.nuf.AsyncFetchSMILMessage.doInBackground.
static SharedPreferences csc440.nuf.Util.getSharedPreferences(Context context)
Helper method to get a SharedPreferences instance.
Referenced by csc440.nuf.Util.generateNotification, csc440.nuf.Util.getRequestFactory, csc440.nuf.AccountsActivity.onCreate, csc440.nuf.C2DMReceiver.onUnregistered, csc440.nuf.DeviceRegistrar.registerOrUnregister, csc440.nuf.SMILActivity.onResume.
static boolean csc440.nuf.Util.isDebug(Context context)
Returns true if we are running against a dev mode appengine instance.
References csc440.nuf.Setup.PROD_URL, csc440.nuf.Util.getBaseUrl.
static String csc440.nuf.Util.getDebugUrl(Context context)
Returns a debug url, or null. To set the url, create a file assets/debugging_prefs.properties with a line of the form 'url=http:/<ip address>="">:<port>'. A numeric IP address may be required in situations where the device or emulator will not be able to resolve the hostname for the dev mode server.
static String csc440.nuf.Util.getPackageName()
Returns the package name of this class.