com::google::appengine::codelab::Util
final Logger com.google.appengine.codelab.Util.logger
DatastoreService com.google.appengine.codelab.Util.datastore
static void com.google.appengine.codelab.Util.persistEntity(Entity entity)
entity : entity to be persisted
Referenced by com.google.appengine.codelab.Item.createOrUpdateItem, com.google.appengine.codelab.Product.createOrUpdateProduct.
static void com.google.appengine.codelab.Util.deleteEntity(Key key)
Delete the entity from persistent store represented by the key key : key to delete the entity from the persistent store
Referenced by com.google.appengine.codelab.Item.deleteItem, com.google.appengine.codelab.Product.deleteProduct.
static void com.google.appengine.codelab.Util.deleteEntity(final List< Key > keys)
Delete list of entities given their keys keys
static Entity com.google.appengine.codelab.Util.findEntity(Key key)
Search and return the entity from datastore. key : key to find the entity entity
Referenced by com.google.appengine.codelab.Product.getProduct.
static Iterable<Entity> com.google.appengine.codelab.Util.listEntities(String kind, String searchBy, String searchFor)
Referenced by com.google.appengine.codelab.Item.getAllItems, com.google.appengine.codelab.Item.getItem, com.google.appengine.codelab.Product.getAllProducts, com.google.appengine.codelab.Util.writeJSON.
static Iterable<Entity> com.google.appengine.codelab.Util.listChildren(String kind, Key ancestor)
Search entities based on ancestor kind ancestor
Referenced by com.google.appengine.codelab.Item.getItemsForProduct.
static Iterable<Entity> com.google.appengine.codelab.Util.listChildKeys(String kind, Key ancestor)
kind ancestor
static String com.google.appengine.codelab.Util.writeJSON(Iterable< Entity > entities)
List the entities in JSON format entities entities to return as JSON strings
Referenced by com.google.appengine.codelab.ItemServlet.doGet, com.google.appengine.codelab.ProductServlet.doGet.
static String com.google.appengine.codelab.Util.writeJSON(Iterable< Entity > entities, String childKind, String fkName)
Retrieves Parent and Child entities into JSON String entities : List of parent entities childKind : Entity type for Child fkName : foreign-key to the parent in the child entity JSON string
References com.google.appengine.codelab.Util.listEntities.
static String com.google.appengine.codelab.Util.getErrorMessage(Exception ex)
Utility method to send the error back to UI data resp IOException
Referenced by com.google.appengine.codelab.ItemServlet.doDelete, com.google.appengine.codelab.ProductServlet.doPut, com.google.appengine.codelab.ProductServlet.doDelete.
static DatastoreService com.google.appengine.codelab.Util.getDatastoreServiceInstance()
get DatastoreService instance DatastoreService instance
Referenced by com.google.appengine.codelab.Item.getSingleItem, com.google.appengine.codelab.Product.getItems.