csc440::nuf::ActionBar
LayoutInflater csc440.nuf.ActionBar.mInflater
ImageView csc440.nuf.ActionBar.mLogoView
TextView csc440.nuf.ActionBar.mTitleView
ProgressBar csc440.nuf.ActionBar.mProgress
LinearLayout csc440.nuf.ActionBar.mActionIconContainer
csc440.nuf.ActionBar.ActionBar(Context context, AttributeSet attrs)
void csc440.nuf.ActionBar.setHomeLogo(int resId)
Referenced by csc440.nuf.SMILActivity.onResume.
void csc440.nuf.ActionBar.setHomeListener(OnClickListener onClickListener)
Referenced by csc440.nuf.ViewMessageActivity.onCreate.
void csc440.nuf.ActionBar.setTitle(CharSequence title)
Referenced by csc440.nuf.SMILActivity.onResume, csc440.nuf.ViewMessageActivity.onCreate.
void csc440.nuf.ActionBar.setTitle(int resid)
void csc440.nuf.ActionBar.showProgressBar()
void csc440.nuf.ActionBar.hideProgressBar()
void csc440.nuf.ActionBar.addActionIcon(int iconResourceId, OnClickListener onClickListener)
Adds ActionIcons to the ActionBar (adds to the left-end) iconResourceId onClickListener to handle click actions on the ActionIcon.
boolean csc440.nuf.ActionBar.removeActionIconAt(int index)
Remove the action icon from the given index (0 based) index true if the item was removed
boolean csc440.nuf.ActionBar.isProgressBarVisible()
true if the progressbar is visible View::VISIBLE
void csc440.nuf.ActionBar.setProgressBarVisibility(int visibility)
Set the enabled state of the progress bar. One of View#VISIBLE, View#INVISIBLE, or View#GONE.