csc440::nuf::ScrollItemManager
LinearLayout csc440.nuf.ScrollItemManager._linear
LinkedList<ScrollItem> csc440.nuf.ScrollItemManager.items
csc440.nuf.ScrollItemManager.ScrollItemManager(View v)
void csc440.nuf.ScrollItemManager.addItem(Context c)
Referenced by csc440.nuf.SMILActivity.onResume, csc440.nuf.ViewMessageActivity.onCreate.
void csc440.nuf.ScrollItemManager.addItem(Context c, boolean useLinear)
void csc440.nuf.ScrollItemManager.setIcon(int resId)
Referenced by csc440.nuf.SMILActivity.onResume, csc440.nuf.ViewMessageActivity.onCreate.
void csc440.nuf.ScrollItemManager.setListener(View.OnClickListener onClickListener, int id)
Referenced by csc440.nuf.SMILActivity.onResume, csc440.nuf.ViewMessageActivity.onCreate.
void csc440.nuf.ScrollItemManager.setTitle(CharSequence title)
Referenced by csc440.nuf.SMILActivity.onResume, csc440.nuf.ViewMessageActivity.onCreate.
void csc440.nuf.ScrollItemManager.setTitle(int resid)
void csc440.nuf.ScrollItemManager.addToLinear(View v)
Referenced by csc440.nuf.ViewMessageActivity.onCreate.
void csc440.nuf.ScrollItemManager.addLine(Context c)
Referenced by csc440.nuf.ViewMessageActivity.onCreate.
void csc440.nuf.ScrollItemManager.setId(int id)