csc440::nuf::server::DataStore
void csc440.nuf.server.DataStore.delete(Long id)
Remove this object from the data store.
Referenced by csc440.nuf.server.SMILEngineService.deleteSMILMessage.
SMILMessage csc440.nuf.server.DataStore.find(Long id)
Find a Task by id. id the SMILMessage id the associated SMILMessage, or null if not found
References csc440.nuf.server.DataStore.getUserEmail.
Referenced by csc440.nuf.server.SMILEngineService.readSMILMessage.
List<SMILMessage> csc440.nuf.server.DataStore.findAll()
References csc440.nuf.server.DataStore.getUserEmail.
Referenced by csc440.nuf.server.SMILEngineService.querySMILMessages.
SMILMessage csc440.nuf.server.DataStore.update(SMILMessage item)
Persist this object in the datastore.
References csc440.nuf.server.SMILMessage.setId, csc440.nuf.server.DataStore.getUserId, csc440.nuf.server.SMILMessage.setSenderEmail, csc440.nuf.server.DataStore.getUserEmail.
Referenced by csc440.nuf.server.SMILEngineService.createSMILMessage, csc440.nuf.server.SMILEngineService.updateSMILMessage.
static String csc440.nuf.server.DataStore.getUserId()
Referenced by csc440.nuf.server.DataStore.update, csc440.nuf.server.SMILEngineService.createSMILMessage, csc440.nuf.server.SMILMessageLocator.create.
static String csc440.nuf.server.DataStore.getUserEmail()
Referenced by csc440.nuf.server.DataStore.find, csc440.nuf.server.DataStore.findAll, csc440.nuf.server.DataStore.update, csc440.nuf.server.SMILEngineService.createSMILMessage, csc440.nuf.server.SMILEngineService.updateSMILMessage, csc440.nuf.server.SMILMessageLocator.create.
static void csc440.nuf.server.DataStore.sendC2DMUpdate(String message)
References csc440.nuf.server.SendMessage.sendMessage.
Referenced by csc440.nuf.server.SMILEngineService.updateSMILMessage.