csc440::nuf::complay::Waiting
Q csc440.nuf.complay.Waiting.q
static Q csc440.nuf.complay.Waiting.Q()
Referenced by csc440.nuf.complay.PlayerActivity.onCreate, csc440.nuf.complay.PlayerCanvas.run, csc440.nuf.complay.Timer.setTime, csc440.nuf.components.SMILText.draw, csc440.nuf.parser.SMILHandler.startElement, csc440.nuf.parser.SMILHandler.endElement, csc440.nuf.parser.SMILHandler.add.