com::thira::examples::actionbar::widget::ActionBar
LayoutInflater com.thira.examples.actionbar.widget.ActionBar.mInflater
Reusable LayoutInflater
ImageView com.thira.examples.actionbar.widget.ActionBar.mLogoView
Holds the home-icon logo
TextView com.thira.examples.actionbar.widget.ActionBar.mTitleView
Displays the Activity text
ProgressBar com.thira.examples.actionbar.widget.ActionBar.mProgress
Represents the progress bar (i.e. busy-icon)
LinearLayout com.thira.examples.actionbar.widget.ActionBar.mActionIconContainer
Contains the ActionIcons.
com.thira.examples.actionbar.widget.ActionBar.ActionBar(Context context, AttributeSet attrs)
void com.thira.examples.actionbar.widget.ActionBar.setHomeLogo(int resId)
Referenced by com.thira.examples.actionbar.CustomTitleActivity.onCreate, com.thira.examples.actionbar.MainActivity.onCreate.
void com.thira.examples.actionbar.widget.ActionBar.setHomeLogo(int resId, OnClickListener onClickListener)
void com.thira.examples.actionbar.widget.ActionBar.setTitle(CharSequence title)
Referenced by com.thira.examples.actionbar.CustomTitleActivity.onCreate, com.thira.examples.actionbar.MainActivity.onCreate.
void com.thira.examples.actionbar.widget.ActionBar.setTitle(int resid)
void com.thira.examples.actionbar.widget.ActionBar.showProgressBar()
Referenced by com.thira.examples.actionbar.MainActivity.onCreate.
void com.thira.examples.actionbar.widget.ActionBar.hideProgressBar()
Referenced by com.thira.examples.actionbar.MainActivity.onCreate.
void com.thira.examples.actionbar.widget.ActionBar.addActionIcon(int iconResourceId, OnClickListener onClickListener)
Adds ActionIcons to the ActionBar (adds to the left-end) iconResourceId onClickListener to handle click actions on the ActionIcon.
Referenced by com.thira.examples.actionbar.CustomTitleActivity.onCreate, com.thira.examples.actionbar.MainActivity.onCreate.
boolean com.thira.examples.actionbar.widget.ActionBar.removeActionIconAt(int index)
Remove the action icon from the given index (0 based) index true if the item was removed
Referenced by com.thira.examples.actionbar.MainActivity.onCreate.
boolean com.thira.examples.actionbar.widget.ActionBar.isProgressBarVisible()
true if the progressbar is visible View::VISIBLE
void com.thira.examples.actionbar.widget.ActionBar.setProgressBarVisibility(int visibility)
Set the enabled state of the progress bar. One of View#VISIBLE, View#INVISIBLE, or View#GONE.