csc440::nuf::complay::PlayerActivity
ImageView csc440.nuf.complay.PlayerActivity._playPause
SeekBar csc440.nuf.complay.PlayerActivity._seekBar
PlayerCanvas csc440.nuf.complay.PlayerActivity._playerCanvas
TextView csc440.nuf.complay.PlayerActivity.timeView
RelativeLayout csc440.nuf.complay.PlayerActivity.controls
boolean csc440.nuf.complay.PlayerActivity.playing
int csc440.nuf.complay.PlayerActivity.messageLength
HideControlsListener csc440.nuf.complay.PlayerActivity.controlHider
RelativeLayout csc440.nuf.complay.PlayerActivity.mainView
boolean csc440.nuf.complay.PlayerActivity.playingCopy
boolean csc440.nuf.complay.PlayerActivity.fromMessage
boolean csc440.nuf.complay.PlayerActivity.playPressed
void csc440.nuf.complay.PlayerActivity.onCreate(Bundle savedInstanceState)
The "main" method of an android activity
References csc440.nuf.complay.Waiting.Q, csc440.nuf.complay.Q.setScreenDensity, csc440.nuf.complay.Q.isEmpty, csc440.nuf.complay.Q.pop, csc440.nuf.complay.Q.push, csc440.nuf.complay.Q.prepQ, csc440.nuf.complay.Q.getMessageLength, csc440.nuf.complay.PlayerCanvas.setSeekBar, csc440.nuf.complay.PlayerActivity.formatSecondsToMinutes, csc440.nuf.complay.PlayerCanvas.setTime.
void csc440.nuf.complay.PlayerActivity.onProgressChanged(SeekBar seekBar, int secondsIn, boolean fromUser)
References csc440.nuf.complay.PlayerActivity.formatSecondsToMinutes, csc440.nuf.complay.PlayerActivity.playPause.
void csc440.nuf.complay.PlayerActivity.onStartTrackingTouch(SeekBar seekBar)
References csc440.nuf.complay.PlayerActivity.playPause.
void csc440.nuf.complay.PlayerActivity.onStopTrackingTouch(SeekBar seekBar)
References csc440.nuf.complay.PlayerActivity.playPause, csc440.nuf.complay.PlayerCanvas.setTime.
void csc440.nuf.complay.PlayerActivity.playPause(View v)
Referenced by csc440.nuf.complay.PlayerActivity.onResume, csc440.nuf.complay.PlayerActivity.onPause, csc440.nuf.complay.PlayerActivity.onProgressChanged, csc440.nuf.complay.PlayerActivity.onStartTrackingTouch, csc440.nuf.complay.PlayerActivity.onStopTrackingTouch.
void csc440.nuf.complay.PlayerActivity.playPause(View v, boolean newPlaying)
References csc440.nuf.complay.PlayerCanvas.setTime, csc440.nuf.complay.PlayerCanvas.play, csc440.nuf.complay.PlayerCanvas.pause.
String csc440.nuf.complay.PlayerActivity.formatSecondsToMinutes(int secondsIn)
Referenced by csc440.nuf.complay.PlayerActivity.onCreate, csc440.nuf.complay.PlayerActivity.onProgressChanged.
void csc440.nuf.complay.PlayerActivity.onResume()
References csc440.nuf.complay.PlayerActivity.playPause.
void csc440.nuf.complay.PlayerActivity.onPause()
References csc440.nuf.complay.PlayerActivity.playPause.