csc440::nuf::DeviceRegistrar
final String csc440.nuf.DeviceRegistrar.ACCOUNT_NAME_EXTRA
Referenced by csc440.nuf.DeviceRegistrar.registerOrUnregister.
final String csc440.nuf.DeviceRegistrar.STATUS_EXTRA
Referenced by csc440.nuf.DeviceRegistrar.registerOrUnregister.
final int csc440.nuf.DeviceRegistrar.REGISTERED_STATUS
Referenced by csc440.nuf.DeviceRegistrar.registerOrUnregister.
final int csc440.nuf.DeviceRegistrar.UNREGISTERED_STATUS
Referenced by csc440.nuf.DeviceRegistrar.registerOrUnregister.
final int csc440.nuf.DeviceRegistrar.ERROR_STATUS
Referenced by csc440.nuf.DeviceRegistrar.registerOrUnregister.
final String csc440.nuf.DeviceRegistrar.TAG
static void csc440.nuf.DeviceRegistrar.registerOrUnregister(final Context context, final String deviceRegistrationId, final boolean register)
References csc440.nuf.Util.getSharedPreferences, csc440.nuf.Util.ACCOUNT_NAME, csc440.nuf.Util.UPDATE_UI_INTENT, csc440.nuf.shared.RegistrationInfoProxy.setDeviceRegistrationId, csc440.nuf.shared.RegistrationInfoProxy.setDeviceId, csc440.nuf.client.MyRequestFactory.RegistrationInfoRequest.register, csc440.nuf.client.MyRequestFactory.RegistrationInfoRequest.unregister, csc440.nuf.Util.AUTH_COOKIE, csc440.nuf.Util.DEVICE_REGISTRATION_ID, csc440.nuf.DeviceRegistrar.ACCOUNT_NAME_EXTRA, csc440.nuf.DeviceRegistrar.STATUS_EXTRA, csc440.nuf.DeviceRegistrar.ERROR_STATUS, csc440.nuf.DeviceRegistrar.REGISTERED_STATUS, csc440.nuf.DeviceRegistrar.UNREGISTERED_STATUS.
Referenced by csc440.nuf.AccountsActivity.onResume, csc440.nuf.C2DMReceiver.onRegistered, csc440.nuf.C2DMReceiver.onUnregistered.
static RegistrationInfoRequest csc440.nuf.DeviceRegistrar.getRequest(Context context)