csc440::nuf::complay::PlayerCanvas
Timer csc440.nuf.complay.PlayerCanvas.timer
boolean csc440.nuf.complay.PlayerCanvas.playing
SurfaceHolder csc440.nuf.complay.PlayerCanvas.holder
Thread csc440.nuf.complay.PlayerCanvas.renderThread
SeekBar csc440.nuf.complay.PlayerCanvas._seekBar
float csc440.nuf.complay.PlayerCanvas.deltaTime
int csc440.nuf.complay.PlayerCanvas.messageLength
csc440.nuf.complay.PlayerCanvas.PlayerCanvas(Context context, AttributeSet attrs)
void csc440.nuf.complay.PlayerCanvas.setSeekBar(SeekBar seekBar)
Referenced by csc440.nuf.complay.PlayerActivity.onCreate.
void csc440.nuf.complay.PlayerCanvas.play()
Referenced by csc440.nuf.complay.PlayerActivity.playPause.
void csc440.nuf.complay.PlayerCanvas.run()
References csc440.nuf.complay.Timer.timePlusPlus, csc440.nuf.complay.OnScreen.Q, csc440.nuf.complay.Q.draw, csc440.nuf.complay.Waiting.Q, csc440.nuf.complay.Q.isEmpty, csc440.nuf.complay.Q.peek, csc440.nuf.complay.Timer.getTime.
void csc440.nuf.complay.PlayerCanvas.pause()
Referenced by csc440.nuf.complay.PlayerActivity.playPause.
void csc440.nuf.complay.PlayerCanvas.setTime(int time)
References csc440.nuf.complay.Timer.setTime.
Referenced by csc440.nuf.complay.PlayerActivity.onCreate, csc440.nuf.complay.PlayerActivity.onStopTrackingTouch, csc440.nuf.complay.PlayerActivity.playPause.
void csc440.nuf.complay.PlayerCanvas.onDraw(Canvas canvas)