csc440::nuf::server::RegistrationInfo
final Logger csc440.nuf.server.RegistrationInfo.log
final int csc440.nuf.server.RegistrationInfo.MAX_DEVICES
String csc440.nuf.server.RegistrationInfo.deviceId
String csc440.nuf.server.RegistrationInfo.deviceRegistrationId
csc440.nuf.server.RegistrationInfo.RegistrationInfo()
String csc440.nuf.server.RegistrationInfo.getDeviceId()
Referenced by csc440.nuf.server.RegistrationInfo.register.
String csc440.nuf.server.RegistrationInfo.getDeviceRegistrationId()
Referenced by csc440.nuf.server.RegistrationInfo.register, csc440.nuf.server.RegistrationInfo.unregister.
void csc440.nuf.server.RegistrationInfo.register()
References csc440.nuf.server.RegistrationInfo.getDeviceRegistrationId, csc440.nuf.server.RegistrationInfo.getDeviceId.
void csc440.nuf.server.RegistrationInfo.setDeviceId(String deviceId)
void csc440.nuf.server.RegistrationInfo.setDeviceRegistrationId(String deviceRegistrationId)
String csc440.nuf.server.RegistrationInfo.toString()
void csc440.nuf.server.RegistrationInfo.unregister()
References csc440.nuf.server.RegistrationInfo.getDeviceRegistrationId.
String csc440.nuf.server.RegistrationInfo.getAccountName()
void csc440.nuf.server.RegistrationInfo.doRegister(String deviceRegistrationId, String deviceType, String deviceId, String accountName)
void csc440.nuf.server.RegistrationInfo.doUnregister(String deviceRegistrationID, String accountName)