com::google::appengine::codelab::Item
static Entity com.google.appengine.codelab.Item.createOrUpdateItem(String productName, String itemName, String price)
Create or update Item for a particular product. Product entity has one to many relation-ship with Item entity productName : product name for which the item is created. itemName : item name price : price of the item
References com.google.appengine.codelab.Product.getProduct, com.google.appengine.codelab.Item.getSingleItem, com.google.appengine.codelab.Util.persistEntity.
Referenced by com.google.appengine.codelab.ItemServlet.doPut.
static Iterable<Entity> com.google.appengine.codelab.Item.getAllItems()
get All the items in the list kind : item kind all the items
References com.google.appengine.codelab.Util.listEntities.
Referenced by com.google.appengine.codelab.ItemServlet.doGet.
static Iterable<Entity> com.google.appengine.codelab.Item.getItem(String itemName)
Get the item by name, return an Iterable itemName : item name Item Entity
References com.google.appengine.codelab.Util.listEntities.
Referenced by com.google.appengine.codelab.ItemServlet.doGet.
static Iterable<Entity> com.google.appengine.codelab.Item.getItemsForProduct(String kind, String productName)
Get all the items for a product kind : item kind productName : product name : all items of type product
References com.google.appengine.codelab.Util.listChildren.
Referenced by com.google.appengine.codelab.ItemServlet.doGet.
static Entity com.google.appengine.codelab.Item.getSingleItem(String itemName)
get Item with item name itemName : get itemName item entity
References com.google.appengine.codelab.Util.getDatastoreServiceInstance.
Referenced by com.google.appengine.codelab.Item.createOrUpdateItem, com.google.appengine.codelab.Item.deleteItem.
static String com.google.appengine.codelab.Item.deleteItem(String itemKey)
References com.google.appengine.codelab.Item.getSingleItem, com.google.appengine.codelab.Util.deleteEntity.
Referenced by com.google.appengine.codelab.ItemServlet.doDelete.