csc440::nuf::complay::Timer
int csc440.nuf.complay.Timer.time
csc440.nuf.complay.Timer.Timer()
int csc440.nuf.complay.Timer.getTime()
Referenced by csc440.nuf.complay.PlayerCanvas.run.
boolean csc440.nuf.complay.Timer.timePlusPlus()
References csc440.nuf.complay.Timer.setTime.
Referenced by csc440.nuf.complay.PlayerCanvas.run.
boolean csc440.nuf.complay.Timer.setTime(int newTime)
References csc440.nuf.complay.OnScreen.Q, csc440.nuf.complay.Q.isEmpty, csc440.nuf.complay.Q.peek, csc440.nuf.complay.OffScreen.Q, csc440.nuf.complay.Q.push, csc440.nuf.complay.Waiting.Q, csc440.nuf.complay.Q.pop, csc440.nuf.complay.Q.sortByEndTimeASC, csc440.nuf.complay.Q.sortByStartTimeDESC.
Referenced by csc440.nuf.complay.PlayerCanvas.setTime, csc440.nuf.complay.Timer.timePlusPlus.