csc440::nuf::components::AbstractSMILObject
String csc440.nuf.components.AbstractSMILObject.qName
Referenced by csc440.nuf.components.AbstractSMILObject.AbstractSMILObject, csc440.nuf.components.SMILImage.SMILImage, csc440.nuf.components.SMILParallel.SMILParallel, csc440.nuf.components.SMILSequential.SMILSequential, csc440.nuf.components.SMILText.SMILText, csc440.nuf.components.SMILVideo.SMILVideo.
int csc440.nuf.components.AbstractSMILObject.begin
Referenced by csc440.nuf.components.AbstractSMILObject.AbstractSMILObject, csc440.nuf.components.AbstractSMILObject.setStartTime, csc440.nuf.components.AbstractSMILObject.getStartTime, csc440.nuf.components.AbstractSMILObject.compareTo, csc440.nuf.components.AbstractSMILObject.toString, csc440.nuf.components.AbstractSMILObject.setDuration, csc440.nuf.components.SMILParallel.add, csc440.nuf.components.SMILSequential.add.
int csc440.nuf.components.AbstractSMILObject.end
Referenced by csc440.nuf.components.AbstractSMILObject.setEndTime, csc440.nuf.components.AbstractSMILObject.getEndTime, csc440.nuf.components.AbstractSMILObject.toString, csc440.nuf.components.AbstractSMILObject.setDuration, csc440.nuf.components.SMILSequential.add.
int csc440.nuf.components.AbstractSMILObject.dur
Referenced by csc440.nuf.components.AbstractSMILObject.toString, csc440.nuf.components.AbstractSMILObject.getDuration, csc440.nuf.components.AbstractSMILObject.setDuration, csc440.nuf.components.SMILSequential.add.
csc440.nuf.components.AbstractSMILObject.AbstractSMILObject(String qName, int begin, int dur)
References csc440.nuf.components.AbstractSMILObject.qName, csc440.nuf.components.AbstractSMILObject.begin, csc440.nuf.components.AbstractSMILObject.setDuration.
csc440.nuf.components.AbstractSMILObject.AbstractSMILObject(Attributes att)
References csc440.nuf.components.AbstractSMILObject.begin, csc440.nuf.components.AbstractSMILObject.setDuration, csc440.nuf.components.AbstractSMILObject.getIntValue.
String csc440.nuf.components.AbstractSMILObject.printTag()
void csc440.nuf.components.AbstractSMILObject.setStartTime(int startTime)
References csc440.nuf.components.AbstractSMILObject.begin.
void csc440.nuf.components.AbstractSMILObject.setEndTime(int endTime)
References csc440.nuf.components.AbstractSMILObject.end.
int csc440.nuf.components.AbstractSMILObject.getStartTime()
References csc440.nuf.components.AbstractSMILObject.begin.
int csc440.nuf.components.AbstractSMILObject.getEndTime()
References csc440.nuf.components.AbstractSMILObject.end.
int csc440.nuf.components.AbstractSMILObject.compareTo(AbstractSMILObject o)
References csc440.nuf.components.AbstractSMILObject.begin.
String csc440.nuf.components.AbstractSMILObject.toString()
References csc440.nuf.components.AbstractSMILObject.begin, csc440.nuf.components.AbstractSMILObject.end, csc440.nuf.components.AbstractSMILObject.dur.
int csc440.nuf.components.AbstractSMILObject.getDuration()
References csc440.nuf.components.AbstractSMILObject.dur.
void csc440.nuf.components.AbstractSMILObject.setDuration(int duration)
References csc440.nuf.components.AbstractSMILObject.dur, csc440.nuf.components.AbstractSMILObject.begin, csc440.nuf.components.AbstractSMILObject.end.
Referenced by csc440.nuf.components.AbstractSMILObject.AbstractSMILObject.
void csc440.nuf.components.AbstractSMILObject.draw(Canvas canvas)
static int csc440.nuf.components.AbstractSMILObject.getIntValue(String s)
Referenced by csc440.nuf.components.AbstractSMILObject.AbstractSMILObject, csc440.nuf.components.SMILImage.SMILImage, csc440.nuf.components.SMILText.SMILText, csc440.nuf.components.SMILVideo.SMILVideo.