com::google::appengine::codelab::Product
static void com.google.appengine.codelab.Product.createOrUpdateProduct(String name, String description)
Update the product name : name of the product description : description updated product
References com.google.appengine.codelab.Product.getProduct, com.google.appengine.codelab.Util.persistEntity.
Referenced by com.google.appengine.codelab.ProductServlet.doPut.
static Iterable<Entity> com.google.appengine.codelab.Product.getAllProducts(String kind)
Retrun all the products kind : of kind product products
References com.google.appengine.codelab.Util.listEntities.
Referenced by com.google.appengine.codelab.ProductServlet.doGet.
static Entity com.google.appengine.codelab.Product.getProduct(String name)
Get product entity name : name of the product : product entity
References com.google.appengine.codelab.Util.findEntity.
Referenced by com.google.appengine.codelab.Item.createOrUpdateItem, com.google.appengine.codelab.Product.createOrUpdateProduct, com.google.appengine.codelab.ProductServlet.doGet.
static List<Entity> com.google.appengine.codelab.Product.getItems(String name)
Get all items for a product name : name of the product list of items
References com.google.appengine.codelab.Util.getDatastoreServiceInstance.
Referenced by com.google.appengine.codelab.Product.deleteProduct.
static String com.google.appengine.codelab.Product.deleteProduct(String productKey)
Delete product entity productKey : product to be deleted status string
References com.google.appengine.codelab.Product.getItems, com.google.appengine.codelab.Util.deleteEntity.
Referenced by com.google.appengine.codelab.ProductServlet.doDelete.