csc440::nuf::complay::Q
LinkedList<AbstractSMILObject> csc440.nuf.complay.Q.objectQ
SMILLayout csc440.nuf.complay.Q.layout
float csc440.nuf.complay.Q.density
String csc440.nuf.complay.Q.qType
csc440.nuf.complay.Q.Q(String qType)
void csc440.nuf.complay.Q.setScreenDensity(float newDensity)
Referenced by csc440.nuf.complay.PlayerActivity.onCreate.
float csc440.nuf.complay.Q.getDensity()
Referenced by csc440.nuf.components.SMILText.draw.
void csc440.nuf.complay.Q.push(AbstractSMILObject smil)
Referenced by csc440.nuf.complay.PlayerActivity.onCreate, csc440.nuf.complay.Timer.setTime, csc440.nuf.parser.SMILHandler.endElement, csc440.nuf.parser.SMILHandler.add.
AbstractSMILObject csc440.nuf.complay.Q.peek()
Referenced by csc440.nuf.complay.PlayerCanvas.run, csc440.nuf.complay.Timer.setTime.
AbstractSMILObject csc440.nuf.complay.Q.pop()
Referenced by csc440.nuf.complay.PlayerActivity.onCreate, csc440.nuf.complay.Timer.setTime.
void csc440.nuf.complay.Q.prepQ()
Referenced by csc440.nuf.complay.PlayerActivity.onCreate.
boolean csc440.nuf.complay.Q.isEmpty()
Referenced by csc440.nuf.complay.PlayerActivity.onCreate, csc440.nuf.complay.PlayerCanvas.run, csc440.nuf.complay.Timer.setTime.
SMILLayout csc440.nuf.complay.Q.getLayout()
void csc440.nuf.complay.Q.setLayout(SMILLayout layout)
Referenced by csc440.nuf.parser.SMILHandler.startElement.
int csc440.nuf.complay.Q.getMessageLength()
Referenced by csc440.nuf.complay.PlayerActivity.onCreate.
int csc440.nuf.complay.Q.getLength()
LinkedList<AbstractSMILObject> csc440.nuf.complay.Q.getQ()
void csc440.nuf.complay.Q.draw(Canvas canvas)
Referenced by csc440.nuf.complay.PlayerCanvas.run.
void csc440.nuf.complay.Q.sortByEndTimeASC()
Referenced by csc440.nuf.complay.Timer.setTime.
void csc440.nuf.complay.Q.sortByStartTimeDESC()
Referenced by csc440.nuf.complay.Timer.setTime.
void csc440.nuf.complay.Q.clear()
void csc440.nuf.complay.Q.logQ(String log)